HBNU-SWUNIV/come-capstone23-f12

003 Code/FE/.idea/workspace.xml, 003 Code/FE/notion-linked-blog/.babelrc, 003 Code/FE/notion-linked-blog/.eslintrc.json, 003 Code/FE/notion-linked-blog/.gitignore, 003 Code/FE/notion-linked-blog/README.md, 003 Code/FE/notion-linked-blog/jsconfig.json, 003 Code/FE/notion-linked-blog/next.config.js, 003 Code/FE/notion-linked-blog/package-lock.json, 003 Code/FE/notion-linked-blog/package.json, 003 Code/FE/notion-linked-blog/src/app/hooks.js, 003 Code/FE/notion-linked-blog/src/app/store.js, 003 Code/FE/notion-linked-blog/src/features/counter/counterSlice.js, 003 Code/FE/notion-linked-blog/src/pages/_app.js, 003 Code/FE/notion-linked-blog/src/pages/index.js
- Trello Card: https://trello.com/c/jbCDkFzP
프론트엔드 개발을 위한 기본 환경 세팅입니다.
=> build: 프론트엔드 기본 개발 환경 세팅

003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/user/UserApiController.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/user/User.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/user/dto/info/UserSearchDto.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/repository/user/UserDataRepository.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/service/user/UserService.java, 003 Code/BE/notion-linked-blog/src/main/resources/application.yml, 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/api/user/UserApiControllerTests.java, 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/repository/user/UserDataRepositoryTest.java, 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/service/user/UserServiceTests.java, 003 Code/BE/notion-linked-blog/src/test/resources/application.yml
- Trello Card: https://trello.com/c/xdd17mfj
- Api: https://www.notion.so/jeidiiy/API-7c2a9051ecbc4f9e8e4d26b6d550a03f?pvs=4
User 조회 수정 삭제 api를 개발했습니다.
- 회원id를 이용해 조회, 수정, 삭제 시행
- 수정 및 삭제시에 Session에 담겨있는 id값 확인
=> feat: 유저 조회, 수정, 삭제 API개발

003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/user/User.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/user/dto/info/UserSearchDto.java, 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/api/user/UserApiControllerTests.java, 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/repository/user/UserDataRepositoryTest.java, 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/service/user/UserServiceTests.java
- Trello Card: https://trello.com/c/tEVpsbdl
- API문서: https://www.notion.so/jeidiiy/API-7c2a9051ecbc4f9e8e4d26b6d550a03f?pvs=4
test코드 오타 수정 및 hashCode 재정의 한 부분을 성능 저하 우려로 제거하였습니다/
- User, UserSearchDto 코드 수정
- hasCode 재정의 부분 제거
- UserApiControllerTests, UserDataRepositoryTests, UserServiceTests 코드 수정
- 오타수정
- hashCode 재정의에 따른 변경사항 반영
=> fix: User, UserSearchDto 코드개선 및 Test코드 오타 수정, 변경 반영

003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/user/UserApiController.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/user/dto/info/UserEditDto.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/service/user/UserService.java, 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/api/user/UserApiControllerTests.java
- Trello Card: https://trello.com/c/sMgCYniy
UserApiController - editUserInfo 수정 및 관련 테스트 코드 변경 반영
- UserEditDto: 수정할 데이터 정보를 받아오는 Dto 별도 생성
- UserApiController: editUserInfo 의 코드 수정
1. APPLICATION_FORM_URLENCODED_VALUE -> Json 으로 변경
- UserApiController 변경에 따른 수정사항 반영
   mockMvc 사용시 contentType 를 APPLICATION_FORM_URLENCODED -> JSON 으로 변경
=> Fix: UserApiController - editUserInfo 수정

003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/config/SecurityConfig.java
- Jira Issues: [F12-62](https://come-capstone23-f12.atlassian.net/jira/software/projects/F12/boards/1?selectedIssue=F12-62)
로그아웃 API 경로 변경
=> fix: 로그아웃 API 경로 /logout -> /api/logout 으로 변경

003 Code/FE/notion-linked-blog/.babelrc, 003 Code/FE/notion-linked-blog/package-lock.json, 003 Code/FE/notion-linked-blog/package.json, 003 Code/FE/notion-linked-blog/src/pages/_document.js
- Jira Issues: [F12-75](https://come-capstone23-f12.atlassian.net/jira/software/projects/F12/boards/1?selectedIssue=F12-75)
- 기타 참조 문서: [Next.js & styled-components - 렌더링 이전에 스타일 적용하기](https://merrily-code.tistory.com/153)
babel-plugin-styled-components 적용 및 _document 파일을 작성하여 Next.js 서버에서 페이지를 받을 때 styled-components 가 적용되도록 하였습니다. 이제 새로고침해도 styled-components로 작성한 css도 정상적으로 적용됩니다.
=> feat: styled-component에 ssr을 적용하여 페이지 로딩 시 styled-comopents 정상 적용

003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/common/Endpoint.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/config/SecurityConfig.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/login/check/dto/LoginStatusCheckingFailureResponseDto.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/login/check/dto/LoginStatusCheckingSuccessResponseDto.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/login/check/filter/LoginStatusCheckingFilter.java, 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/security/login/check/filter/LoginStatusCheckingFilterTests.java
- Jira Issues: [F12-81](https://come-capstone23-f12.atlassian.net/jira/software/projects/F12/boards/1?selectedIssue=F12-81)
로그인 상태를 확인하기 위한 API를 Filter 기반으로 구현하여 SpringSecurity의 FilterChain에 추가하였습니다.
- [warn: SPRING_SECURITY_CONTEXT did not contain a SecurityContext but contained](https://somuchthings.tistory.com/297)
=> feat: 로그인 상태 확인을 위한 API 개발

003 Code/FE/notion-linked-blog/package-lock.json, 003 Code/FE/notion-linked-blog/package.json, 003 Code/FE/notion-linked-blog/src/pages/_app.js, 003 Code/FE/notion-linked-blog/src/redux/store.js
- Jira Issues: [F12-85](https://come-capstone23-f12.atlassian.net/browse/F12-85)
- 기타 참조 문서: https://nextjs.org/docs/messages/react-hydration-error
Hydration 관련 오류를 수정하고 SSR & CSR 에서 Redux를 통합했습니다.
=> fix: Hydration 관련 오류 수정 및 Next.js에서 SSR, CSR Redux 통합

003 Code/FE/notion-linked-blog/.eslintrc.json, 003 Code/FE/notion-linked-blog/package-lock.json, 003 Code/FE/notion-linked-blog/package.json, 003 Code/FE/notion-linked-blog/src/apis/post.js, 003 Code/FE/notion-linked-blog/src/components/auth/LoginForm.jsx, 003 Code/FE/notion-linked-blog/src/components/auth/SignupForm.jsx, 003 Code/FE/notion-linked-blog/src/components/auth/common.js, 003 Code/FE/notion-linked-blog/src/components/common/AppHeader.jsx, 003 Code/FE/notion-linked-blog/src/components/post/Post.js, 003 Code/FE/notion-linked-blog/src/components/post/PostWrite.jsx, 003 Code/FE/notion-linked-blog/src/components/post/PostWriteSetting.jsx, 003 Code/FE/notion-linked-blog/src/components/post/Uploader.jsx, 003 Code/FE/notion-linked-blog/src/pages/write.js, 003 Code/FE/notion-linked-blog/src/redux/postSlice.js
- Jira Issues: [F12-86](https://come-capstone23-f12.atlassian.net/browse/F12-86) 
Post를 작성할 수 있는 관련 컴포넌트들을 개발했습니다.
=> feat: 포스트 작성 컴포넌트 개발

003 Code/FE/notion-linked-blog/src/components/auth/LoginForm.jsx, 003 Code/FE/notion-linked-blog/src/components/auth/SignupForm.jsx, 003 Code/FE/notion-linked-blog/src/components/auth/common.js, 003 Code/FE/notion-linked-blog/src/components/post/Post.js, 003 Code/FE/notion-linked-blog/src/components/post/PostWriteSetting.jsx, 003 Code/FE/notion-linked-blog/src/pages/write.js
- Jira Issues: [F12-87](https://come-capstone23-f12.atlassian.net/browse/F12-87?atlOrigin=eyJpIjoiZTUzNWQ5ZmU1ZTVhNDhiNGJkMzBjMjQ4ZjQ1MjZiNGYiLCJwIjoiaiJ9) [F12-88](https://come-capstone23-f12.atlassian.net/browse/F12-88?atlOrigin=eyJpIjoiMmM3YTUxYzkwZWE0NGFjOGJkYjc5YmQ2NWQ5YzlhZGUiLCJwIjoiaiJ9) 
- 회원가입시 이메일, 비밀번호 정규식 추가 
- 잘못된 인증코드 입력시 시간이 사라지는 버그 수정 
- 로그인 및 회원가입 오류 처리
=> fix: 로그인 및 회원가입 오류 수정 및 개선

003 Code/FE/notion-linked-blog/package-lock.json, 003 Code/FE/notion-linked-blog/src/components/auth/SignupForm.jsx, 003 Code/FE/notion-linked-blog/src/components/post/PostWriteSetting.jsx, 003 Code/FE/notion-linked-blog/src/pages/write.js
Jira Issues: [F12-88](https://come-capstone23-f12.atlassian.net/browse/F12-88?atlOrigin=eyJpIjoiMmM3YTUxYzkwZWE0NGFjOGJkYjc5YmQ2NWQ5YzlhZGUiLCJwIjoiaiJ9)
회원가입 오류처리 코드를 개선하였습니다.
포스트의 요약 설명 및 공개 범위를 보내는 데이터에 추가하였습니다.
=> refactor: 회원가입 오류처리 코드 개선 및 포스트에서 보내는 데이터 추가

003 Code/FE/notion-linked-blog/src/apis/post.js, 003 Code/FE/notion-linked-blog/src/components/auth/SignupForm.jsx, 003 Code/FE/notion-linked-blog/src/components/common/AppHeader.jsx, 003 Code/FE/notion-linked-blog/src/components/post/MainPosts.jsx, 003 Code/FE/notion-linked-blog/src/components/post/PostCard.jsx, 003 Code/FE/notion-linked-blog/src/components/post/PostViewer.jsx, 003 Code/FE/notion-linked-blog/src/pages/[author]/[id].js, 003 Code/FE/notion-linked-blog/src/utils/time.js
⚠️현재 스프린트가 종료된 관계로 Jira의 이슈를 참조할 수 없습니다.
개별 포스트 조회 기능을 개발하고 기타 반응형 작업을 수행했습니다.
=> feat: 개별 포스트 조회 기능 개발

003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/api/post/PostApiControllerTest.java
⚠️현재 스프린트가 종료된 관계로 Jira의 이슈를 참조할 수 없습니다.
API 응답 코드 수정에 따른 테스트 실패 이슈를 수정했습니다.
=> fix: PostApiControllerTest의 포스트 수정 이슈 해결

003 Code/FE/notion-linked-blog/src/components/common/AppHeader.tsx, 003 Code/FE/notion-linked-blog/src/components/common/MenuItem.tsx, 003 Code/FE/notion-linked-blog/src/components/common/MenuItemsDropdown.tsx, 003 Code/FE/notion-linked-blog/src/pages/logout/index.tsx, 003 Code/FE/notion-linked-blog/src/types/index.ts
- Jira Issues: [F12-97](https://come-capstone23-f12.atlassian.net/browse/F12-97)
TypeScript의 enum을 기반으로 하드코딩된 사용자 드롭다운 메뉴를 리팩토링했습니다.
=> refactor: 사용자 드롭다운 메뉴 리팩토링

003 Code/FE/notion-linked-blog/src/apis/signup.ts, 003 Code/FE/notion-linked-blog/src/components/auth/SignupForm.tsx, 003 Code/FE/notion-linked-blog/src/components/post/PostViewer.tsx, 003 Code/FE/notion-linked-blog/src/pages/write/[id].tsx
- Jira Issues: [F12-99](https://come-capstone23-f12.atlassian.net/browse/F12-99)
회원 가입 시 기존에 없던 자기소개, 소셜 링크 등을 추가했습니다.
|기능|스크린샷|
|---|-------|
|IMAGE|![image](https://github.com/HBNU-SWUNIV/come-capstone23-f12/assets/57584529/2a89cfff-3923-4270-862c-03c7d2c5c6c6)|
=> feat: 회원 가입 시 기타 필드 추가

003 Code/FE/notion-linked-blog/src/apis/user.ts, 003 Code/FE/notion-linked-blog/src/components/setting/BottomInfo.tsx, 003 Code/FE/notion-linked-blog/src/components/setting/TopInfo.tsx, 003 Code/FE/notion-linked-blog/src/components/setting/bottom/BlogInfo.tsx, 003 Code/FE/notion-linked-blog/src/components/setting/bottom/BottomInfoItem.tsx, 003 Code/FE/notion-linked-blog/src/components/setting/bottom/SettingSubtitle.tsx, 003 Code/FE/notion-linked-blog/src/components/setting/bottom/Signout.tsx, 003 Code/FE/notion-linked-blog/src/components/setting/bottom/SocialInfo.tsx, 003 Code/FE/notion-linked-blog/src/components/setting/top/Introduction.tsx, 003 Code/FE/notion-linked-blog/src/components/setting/top/Profile.tsx, 003 Code/FE/notion-linked-blog/src/pages/setting/index.tsx
- Jira Issues: [F12-100](https://come-capstone23-f12.atlassian.net/browse/F12-100)
세팅 페이지 관련 컴포넌트 및 회원탈퇴 기능을 개발했습니다.
|기능|스크린샷|
|---|-------|
|IMAGE|![image](https://github.com/HBNU-SWUNIV/come-capstone23-f12/assets/57584529/5f33be04-08ef-473a-8d06-888d47ac5c1d)|
|회원탈퇴 GIF|![signout](https://github.com/HBNU-SWUNIV/come-capstone23-f12/assets/57584529/b6c8eb5a-ece4-41e6-acff-4334c94440b1)|
=> feat: 사용자 정보 수정 페이지 및 컴포넌트 개발, 회원탈퇴 기능 개발

003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/config/Utf8Filter.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/config/WebConfig.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/config/SecurityConfig.java
- Jira Issues: [F12-102](https://come-capstone23-f12.atlassian.net/jira/software/projects/F12/boards/1?selectedIssue=F12-102)
- 기타 참조 문서: [StackOverFlow](https://stackoverflow.com/questions/20863489/characterencodingfilter-dont-work-together-with-spring-security-3-2-0/23051264#23051264)
요약글 - Security부분은 response에 직접 charset을 붙여줌으로써, 나머지는 UrlPattern 에 따라 charset을 붙임
- 직접 CharacterEncoding과 ContentType을 넣어줌으로써 Encoding 설정
``` java
@Bean
public AuthenticationEntryPoint authenticationEntryPoint() {
return (request, response, authException) -> {
log.info("BasicAuthenticationEntryPoint.commence() 실행");
ObjectMapper objectMapper = new ObjectMapper();
AuthenticationFailureDto authenticationFailureDto = AuthenticationFailureDto.getInstance();
response.setStatus(HttpStatus.UNAUTHORIZED.value()); …
```
=> fix: encoding 문제 해결

003 Code/FE/notion-linked-blog/package-lock.json, 003 Code/FE/notion-linked-blog/package.json, 003 Code/FE/notion-linked-blog/src/components/auth/SignupForm.tsx, 003 Code/FE/notion-linked-blog/src/components/post/PostWriteSetting.tsx, 003 Code/FE/notion-linked-blog/src/components/post/comment/Comment.tsx, 003 Code/FE/notion-linked-blog/src/components/post/comment/CommentContainer.tsx, 003 Code/FE/notion-linked-blog/src/components/post/comment/CommentForm.tsx, 003 Code/FE/notion-linked-blog/src/components/post/comment/CommentWriterDetails.tsx, 003 Code/FE/notion-linked-blog/src/pages/[author]/[id].tsx
- Jira Issues: [F12-106](https://come-capstone23-f12.atlassian.net/browse/F12-106)
댓글 작성 폼 및 작성된 댓글 컴포넌트를 개발했습니다.
|기능|스크린샷|
|---|-------|
|IMAGE|![image](https://github.com/HBNU-SWUNIV/come-capstone23-f12/assets/57584529/6ac421b2-6c47-4d69-b238-54140d912ab0)|
=> feat: 댓글 컴포넌트 개발

003 Code/FE/notion-linked-blog/src/apis/post.ts, 003 Code/FE/notion-linked-blog/src/apis/signup.ts, 003 Code/FE/notion-linked-blog/src/apis/user.ts, 003 Code/FE/notion-linked-blog/src/components/post/PostCard.tsx
- Jira Issues: [F12-107](https://come-capstone23-f12.atlassian.net/browse/F12-107)
메인 페이지의 포스트 카드에 썸네일 이미지를 추가했습니다.
|기능|스크린샷|
|---|-------|
|IMAGE|![image](https://github.com/HBNU-SWUNIV/come-capstone23-f12/assets/57584529/e44d18bf-a6af-4097-8df0-b1da0f7e5f2d)|
=> feat: 메인 페이지의 포스트카드에 썸네일 추가

003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/aop/exception/DefaultRestControllerAdvice.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/user/UserApiController.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/component/NotionDevComponent.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/component/oauth/NotionOAuthComponent.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/user/dto/response/NoUserProfileDto.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/domain/user/dto/response/UserSearchDto.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/exceptions/exception/NoProfileImageException.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/exceptions/message/ExceptionMessages.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/repository/user/UserDataRepository.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/service/notion/NotionService.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/service/oauth/NotionOauthService.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/service/post/PostService.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/service/user/UserService.java, 003 Code/BE/notion-linked-blog/src/main/resources/application.yml, 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/api/post/PostApiControllerTest.java, 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/repository/user/UserDataRepositoryTest.java, 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/service/user/UserServiceTests.java, 003 Code/BE/notion-linked-blog/src/test/resources/application.yml
- Jira Issues
1. [F12-114](https://come-capstone23-f12.atlassian.net/jira/software/projects/F12/boards/1?selectedIssue=F12-114)
user기능 중 ProfileImage 미존재시 리턴값 삭제 및 post 조회시 작성자 프로파일 이미지 추가
- user기능 중 ProfileImage 미존재시 리턴값 삭제
- post 조회시 작성자 프로파일 이미지 추가
=> feat: user 기능 변경 및 post 반환 데이터 추가

003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/login/ajax/dto/UserWithoutPassword.java
- Jira Issues: [F12-114](https://come-capstone23-f12.atlassian.net/jira/software/projects/F12/boards/1?selectedIssue=F12-114)
- 기존 PR: #89 
유저의 정보 반환시 notion 연동 여부 확인
- 누락되어있던 로그인시 notion 연동 여부 확인부분 추가
|기능|스크린샷|
|---|-------|
|로그인시 JSON|![image](https://github.com/HBNU-SWUNIV/come-capstone23-f12/assets/46470302/15abc866-b0b2-448b-96d8-da83669b676a)|
=> fix: user 기능추가시 누락부분 반영

003 Code/FE/notion-linked-blog/src/components/setting/bottom/NotionLinking.tsx, 003 Code/FE/notion-linked-blog/src/pages/auth.tsx
- Jira Issues: [F12-115](https://come-capstone23-f12.atlassian.net/browse/F12-115)
노션 연동 시 연동 과정에서 연동 중임을 나타내는 UI 처리를 했습니다.
|기능|스크린샷|
|---|-------|
|GIF|![notionlinkingloading](https://github.com/HBNU-SWUNIV/come-capstone23-f12/assets/57584529/dcc658cd-b712-4d57-9e40-5dddc7bc2544)|
=> feat: 노션 연동 시 로딩 UI 처리

003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/hashtag/exception/HashtagExceptionMessage.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/hashtag/exception/NoHashtagException.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/hashtag/serivce/HashtagServiceImpl.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/infrastructure/SyncedPagesEntity.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/oauth/infrastructure/NotionOauthEntity.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/post/api/PostApiController.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/post/api/port/PostService.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/post/domain/dto/HashtagSearchDto.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/post/infrastructure/PostEntity.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/post/infrastructure/PostQuerydslRepositoryImpl.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/post/service/PostServiceImpl.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/post/service/port/HashtagService.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/infrastructure/UserEntity.java, 003 Code/BE/notion-linked-blog/src/main/resources/data.sql, 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/medium/post/service/PostServiceTest.java
- Jira Issues: [F12-11](https://come-capstone23-f12.atlassian.net/jira/software/projects/F12/boards/1?selectedIssue=F12-11)
- 기타 참조 문서:
hashtag 기능추가 및 기타 버그 수정
- Post로 조회시 Hashtag 기능 추가
- 더미 데이터 추가
- FetchType Lazy가 설정되지 않은 *ToOne 설정 변경
=> feat: hashtag 기능추가 2

003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/post/service/PostServiceImpl.java, 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/common/config/TestQuerydslConfiguration.java
- Jira Issues: [F12-121](https://come-capstone23-f12.atlassian.net/jira/software/projects/F12/boards/1?selectedIssue=F12-121)
Test 오류 해
- Test시 Bean 미등록 오류를 해결
- Hashtag 조회시 null 처리에서 생긴 문제 해결 추가
=> fix: 테스트 오류 해결

003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/oauth/common/domain/CreateOauthAttribute.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/oauth/common/domain/OAuthAttributes.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/oauth/common/service/CustomOAuth2UserDetailsService.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/oauth/github/GithubOAuth2RequestEntityConverter.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/oauth/github/GithubOAuth2UserService.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/oauth/github/dto/GithubOauthEmailEntity.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/infrastructure/UserDataRepository.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/infrastructure/UserEntity.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/service/port/UserRepository.java
- Jira Issues: [F12-122](https://come-capstone23-f12.atlassian.net/jira/software/projects/F12/boards/1?selectedIssue=F12-122)
Github Oauth2 로그인 기능 추가
- 깃허브 oauth2  로그인 기능 추가
- 자신의 email 공유 상태에 따라 로그인이 안되는 현상 해결
- github, google, email 회원가입 사용자의 구분과 email 필드의 중복을 막기 위해 oauth로그인 시 접두사 추
- X
=> feat: github 로그인 기능

003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/common/aop/exception/DefaultRestControllerAdvice.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/api/NotionApiController.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/api/port/NotionService.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/domain/SyncedPages.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/domain/dto/CreateNotionPageToBlogDto.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/exception/NoContentException.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/infrastructure/SyncedPagesDataRepository.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/infrastructure/multi/SyncedSeriesDataRepository.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/infrastructure/multi/SyncedSeriesEntity.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/infrastructure/single/SyncedPagesDataRepository.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/infrastructure/single/SyncedPagesEntity.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/service/NotionServiceImpl.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/service/UpdateNotionSchedule.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/service/port/SyncedPagesRepository.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/service/port/SyncedSeriesRepository.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/oauth/notion/api/OAuthApiController.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/oauth/notion/service/NotionOauthServiceImpl.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/post/infrastructure/PostEntity.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/series/infrastructure/SeriesEntity.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/infrastructure/UserEntity.java
- Jira Issues: [F12-123](https://come-capstone23-f12.atlassian.net/browse/F12-123)
노션 다건, 단건 연동 기능 추가
- 노션 단건 연동 기능 개선
- 기존 테스트 용도에서  실제 사용 용도로 변경
- 노션 다건 연동 기능 추가
- Post와 같이 1시간마다 검사 이후 업데이트가 필요한 경우에 진행
=> feat: notion 연동 기능 개선 및 강화

003 Code/FE/notion-linked-blog/src/components/post/PostViewer.tsx
- props 오류로 인한 Next 빌드 에러를 수정했습니다.
=> fix: props 오류로 인한 빌드 에러 수정

003 Code/BE/notion-linked-blog/build.gradle, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/common/aop/exception/DefaultRestControllerAdvice.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/api/NotionApiController.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/api/port/NotionService.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/domain/SyncedPages.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/domain/dto/CreateNotionPageToBlogDto.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/exception/NoContentException.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/infrastructure/multi/SyncedSeriesDataRepository.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/infrastructure/multi/SyncedSeriesEntity.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/infrastructure/single/SyncedPagesDataRepository.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/infrastructure/single/SyncedPagesEntity.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/service/NotionServiceImpl.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/service/UpdateNotionSchedule.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/service/port/SyncedPagesRepository.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/service/port/SyncedSeriesRepository.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/oauth/notion/api/OAuthApiController.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/oauth/notion/service/NotionOauthServiceImpl.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/post/infrastructure/PostEntity.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/series/infrastructure/SeriesEntity.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/infrastructure/UserEntity.java, 003 Code/BE/notion-linked-blog/src/main/resources/application.yml, 003 Code/FE/notion-linked-blog/src/components/post/PostViewer.tsx
- Jira Issues: [F12-126](https://come-capstone23-f12.atlassian.net/jira/software/projects/F12/boards/1?selectedIssue=F12-126)
yaml 파일을 분리하여 dev, prod 분리
- 실행시에 dev 파일은 --spring.profiles.active=dev 옵션을 붙여 실행
- 실행시에 prod 파일은 --spring.profiles.active=prod 옵션을 붙여 실행
=> build: 서버 배포를 위한 스프링 설정파일 분리

003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/comments/api/CommentsApiController.java
- Jira Issues: [F12-127](https://come-capstone23-f12.atlassian.net/jira/software/projects/F12/boards/1?selectedIssue=F12-127)
PathVariable이 잘못 설정되어있던 부분 수정
=> fix: 변수 이름 수정

003 Code/BE/notion-linked-blog/Dockerfile, 003 Code/BE/notion-linked-blog/build.gradle, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/common/config/EmbeddedRedisConfig.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/common/config/RedisConfig.java
- Jira Issues1: [F12-128](https://come-capstone23-f12.atlassian.net/jira/software/projects/F12/boards/1?selectedIssue=F12-128)
- Jira Issues2: [F12-129](https://come-capstone23-f12.atlassian.net/jira/software/projects/F12/boards/1?selectedIssue=F12-129)
개발 환경 분리 및 Dockerfile 작성
- dev, pord로 spring 개발 환경 분리 및 적용
- Dockerfile 작성
-  빌드된 Dockerfile은 dockerhub에 게시
=> feat: 배포를 위한 환경 분리 및 dockerfile작성

003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/common/config/DevRedisConfig.java, 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/common/config/EmbeddedRedisConfig.java, 003 Code/BE/notion-linked-blog/src/test/resources/application.yml
- Jira Issues: [F12-131](https://come-capstone23-f12.atlassian.net/jira/software/projects/F12/boards/1?selectedIssue=F12-131)
redis가 환경 분리 이후 실행되지 않는 현상 해결
- #108
=> fix: Redis 테스트 오류 해결

003 Code/BE/notion-linked-blog/build.gradle, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/common/config/AwsConfig.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/common/config/DevRedisConfig.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/common/domain/AwsBucket.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/post/api/PostApiController.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/post/api/port/PostService.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/post/api/response/PostThumbnailDto.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/post/infrastructure/PostDataRepository.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/post/infrastructure/PostEntity.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/post/service/PostServiceImpl.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/post/service/port/PostRepository.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/api/UserApiController.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/api/port/UserService.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/api/response/ProfileImageLinkDto.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/service/UserServiceImpl.java, 003 Code/BE/notion-linked-blog/src/main/resources/application.yml, 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/common/config/EmbeddedRedisConfig.java, 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/medium/post/api/PostApiControllerTest.java, 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/medium/post/infrastructure/PostDataRepositoryTest.java, 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/medium/post/service/PostServiceTest.java, 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/medium/user/api/UserApiControllerTests.java, 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/medium/user/service/UserServiceTests.java, 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/small/mock/FakePostRepository.java, 003 Code/BE/notion-linked-blog/src/test/resources/application.yml
- Jira Issues: [F12-132](https://come-capstone23-f12.atlassian.net/jira/software/projects/F12/boards/1?selectedIssue=F12-132)
- Jira Issues: [F12-133](https://come-capstone23-f12.atlassian.net/jira/software/projects/F12/boards/1?selectedIssue=F12-133)
이미지들의 저장위치 local -> s3Bucket으로 이동 및 thumbnail 변경 매서드 추가
- post 썸네일 저장위치 변경
- user 프로필 이미지 저장위치 변경
- 썸네일 변경 매서드 추가
=> feat: 이미지들의 저장위치 local -> s3Bucket으로 이동 및 thumbnail 변경 매서드 추가

003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/api/UserApiController.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/api/port/UserService.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/service/UserServiceImpl.java, 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/medium/user/api/UserApiControllerTests.java
- Jira Issues:[F12-134](https://come-capstone23-f12.atlassian.net/jira/software/projects/F12/boards/1?selectedIssue=F12-134)
profile 이미지 삭제 오류 해결
- profile 이미지 삭제 오류 해결
- 리턴시 204 -> 200으로 변경
- 리턴시 json타입으로 링크 리턴
=> fix: profile 이미지 삭제 오류 해결

003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/comments/api/response/ChildCommentDto.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/comments/api/response/ParentsCommentDto.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/comments/service/CommentsServiceImpl.java, 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/medium/comments/service/CommentsServiceTest.java
- Jira Issues:[F12-135](https://come-capstone23-f12.atlassian.net/jira/software/projects/F12/boards/1?selectedIssue=F12-135)
comment에 바뀐 profileImage 경로 반영 안되는 버그 수정
=> fix: comment에 바뀐 profileImage 경로 반영 안되는 버그 수정

003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/common/domain/EntityConverter.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/post/infrastructure/PostQuerydslRepositoryImpl.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/post/service/PostServiceImpl.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/security/config/SecurityConfig.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/series/infrastructure/SeriesQuerydslRepository.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/api/UserApiController.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/api/port/UserService.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/api/response/UserPostsDto.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/api/response/UserSeriesDto.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/domain/dto/UserSeriesInfoDto.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/service/UserServiceImpl.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/service/port/UserPostQuerydslRepository.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/service/port/UserRepository.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/service/port/UserSeriesQuerydslRepository.java, 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/medium/post/service/PostServiceTest.java
- Jira Issues:[F12-136](https://come-capstone23-f12.atlassian.net/jira/software/projects/F12/boards/1?selectedIssue=F12-136)
userId로 post와 series 검색 매서드 추가
- user의 post검색 기능 추가
- user의 series검색 기능 추가
swagger 참조
=> feat: userId로 post와 series 검색 매서드 추가

003 Code/FE/notion-linked-blog/src/apis/user.ts, 003 Code/FE/notion-linked-blog/src/components/common/MenuItemsDropdown.tsx, 003 Code/FE/notion-linked-blog/src/components/common/menuItemData.json, 003 Code/FE/notion-linked-blog/src/pages/[author]/index.tsx
- 내가 쓴 글을 조회하는 기능을 개발했습니다.
|기능|스크린샷|
|---|-------|
|GIF|![notionlinkedblogMyBlog](https://github.com/HBNU-SWUNIV/come-capstone23-f12/assets/57584529/0536a578-ed36-4b7a-9c04-dca8fdaee1e0)|
=> feat: 내 블로그 기능 개발

003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/api/UserApiController.java
- Jira Issues: [F12-137](https://come-capstone23-f12.atlassian.net/jira/software/projects/F12/boards/1?selectedIssue=F12-137)
swagger가 UserSeriesDto를 보여주지 못하는 오류 발견으로 인해 example로 대체
|기능|스크린샷|
|---|-------|
|swagger|![image](https://github.com/HBNU-SWUNIV/come-capstone23-f12/assets/46470302/530c0182-d407-41e3-9bf7-5d0086ac99cd)|
=> fix: swagger오류 임시 해결

003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/common/domain/EntityConverter.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/series/api/SeriesApiController.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/series/api/port/SeriesService.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/series/api/response/SeriesDetailSearchDto.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/series/api/response/SeriesSimpleSearchDto.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/series/api/response/UserSeriesResponseDto.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/series/infrastructure/SeriesQuerydslRepository.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/series/service/SeriesServiceImpl.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/user/domain/dto/UserSeriesInfoDto.java, 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/medium/series/service/SeriesServiceTest.java
- Jira Issues:[F12-138](https://come-capstone23-f12.atlassian.net/jira/software/projects/F12/boards/1?selectedIssue=F12-138)
series리턴타입 파라미터 추가 및 Series에서 내려주는 ThumbnailUrl 변경
- series 리턴시 authorId, author 두개 파라미터 추가
- series에서 post조회 후 thumbnailUrl을 내려줄 때 미 변경된 부분 변경 추가
=> fix: series리턴파라미터 추가 및 Series에서 내려주는 ThumbnailUrl 변경

003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/common/aop/exception/DefaultRestControllerAdvice.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/common/domain/EntityConverter.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/post/api/PostApiController.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/series/api/SeriesApiController.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/series/api/port/SeriesService.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/series/api/response/PostForDetailSeries.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/series/exception/SeriesNotExistException.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/series/service/SeriesServiceImpl.java, 003 Code/BE/notion-linked-blog/src/test/java/io/f12/notionlinkedblog/medium/series/service/SeriesServiceTest.java
- Jira Issues: [F12-139](https://come-capstone23-f12.atlassian.net/jira/software/projects/F12/boards/1?selectedIssue=F12-139)
series관련 api 수정 및 예외처리 추가
- series detail 조회 시에 postId 추
- detail 조회 시 series가 없는 경우에 에러
- 포스트 생성 시 seriesId를 넣어줘도 추가되지 않는 오류 - Transactional 에러
=> fix: series관련 api 수정 및 예외처리 추가

003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/service/NotionServiceImpl.java
- Jira Issues: [F12-140](https://come-capstone23-f12.atlassian.net/jira/software/projects/F12/boards/1?selectedIssue=F12-140)
- 기타 참조 문서:
convertPathToId 에서 쿼리 파라미터를 분리하지 못하는 문제 해결
=> fix: convertPathToId 에서 쿼리 파라미터를 분리하지 못하는 문제 해결

003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/common/aop/exception/DefaultRestControllerAdvice.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/api/NotionApiController.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/api/port/NotionService.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/exception/NoAccessTokenException.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/exception/NoTitleException.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/service/NotionServiceImpl.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/notion/service/UpdateNotionSchedule.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/oauth/notion/api/OAuthApiController.java, 003 Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/post/infrastructure/PostEntity.java
예외처리 및 Token조회 관련 버그 수정 및 토큰의 호환성 추가
=> fix: 예외처리 및 Token조회 관련 버그 수정
